#:kivy 2.0.0

GridLayout:
    cols: 4  # 5 ปุ่มต่อแถว
    spacing: 10
    padding: 10

    Label:
        id: score_label
        text: "Score: 0"
        font_size: 24
        size_hint: (1, 0.2)
        colspan: 5

    Button:
        id: start_button
        text: "Start Game"
        font_size: 20
        size_hint: (1, 0.5)
        background_color: [0, 1,0, 1]
        pos_hint: {"center_x": 0.5, "center_y": 0.5}

